### ISSUE TITLE
Is there an official package on npmjs.org?

### ISSUE THREAD

**Issue by ehirsch** [trello/scientist#11]
I'm just wondering if you have published this package anywhere. And if not - why.

This really looks good and I'd like to use it ;)

**Comment by dpatti** [comment]
Yes! It's simply called [scientist](https://www.npmjs.com/package/scientist). I realize that's not apparent at all coming from GitHub, so I can add an npm badge to the README.

**Comment by ehirsch** [comment]
Never mind - found it.

**Comment by ehirsch** [comment]
wow - you were fast! A badge would be great thou.

**Comment by dpatti** [comment]
Added!
