### ISSUE TITLE
Getting started example

### ISSUE THREAD

**Issue by maheshsundaram** [trello/scientist#12]
In the 'Getting started' section of the `README.md`, the example code includes:

```
const Scientist = require('./index');
```

Shouldn't this instead reference the npm package? I.e.

```
const Scientist = require('scientist');
```

**Comment by dpatti** [comment]
That certainly looks wrong to me. I changed it to `require('scientist')`. I think when writing that, I may have copied the source of `console.js`, which _was_ using `require('./index')`. Thanks for bringing it up!
