### ISSUE TITLE
Why Reuse startTime for Observations?

### ISSUE THREAD

**Issue by DavidTPate** [trello/scientist#3]
While looking through the code it looks like when dealing with multiple Observations (or Promises) the `startTime` is re-used from initial execution of the mapping instead of just prior to the execution of the experiment. 

I see why this is done for Promises because it is created just prior to the Promise being returned and then re-used to create a new observation once settled.

It just seems like this would inflate results just ever so much to show that they are slower than they actually are.

**Comment by dpatti** [comment]
I think I understand what you're saying. There are three places that observations are created: the initial trial, the mapping, and in async mode, the settling. So in async mode, `duration` is the span from when the trial was started to when the settle completed, which is basically what we want and probably as good as we're going to get. In sync mode, `duration` is the span from when the trial was started to when the _mapping_ completed, in which case you pay a penalty for both the mapping and the time it took to execute all other trials. Is that what you were getting at?

**Comment by DavidTPate** [comment]
Yeah, for `async mode` I think what is going on is correct, but for `sync mode` I think it is incorrect because of the reason that you mentioned:

> In sync mode, duration is the span from when the trial was started to when the mapping completed, in which case you pay a penalty for both the mapping and the time it took to execute all other trials.
